### ISSUE TITLE
please help, stuck in something

### ISSUE THREAD

**Issue by ovidiu31** [zymotik/it500#7]
Hello

I am trying to setup my salus IT500 with home assistant and ive got stuck in something , please help me out.
I attach the log here : http://paste.ubuntu.com/p/JcSnGPnB5X/

much appreciating

**Comment by ovidiu31** [comment]
also in console getting this:
`root@orangepi4:~/it500# npm run start

> salus-it500-mqtt@1.0.0 start /home/ovi/it500
> node index.js

No .\settings.json file found. Create one from the .\settings.sample.json file.
29/07/2020 09:21:02 it500 MQTT publish program starting.
29/07/2020 09:21:02 Timer set to publish every 60 seconds.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/home/ovi/it500/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/home/ovi/it500/node_modules/mqtt/lib/client.js:350:12)
    at work (/home/ovi/it500/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/home/ovi/it500/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/home/ovi/it500/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/ovi/it500/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/home/ovi/it500/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:716:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
Emitted 'error' event on MqttClient instance at:
    at MqttClient._handleConnack (/home/ovi/it500/node_modules/mqtt/lib/client.js:922:10)
    at MqttClient._handlePacket (/home/ovi/it500/node_modules/mqtt/lib/client.js:350:12)
    [... lines matching original stack trace ...]
    at addChunk (_stream_readable.js:295:12) {
  code: 5
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! salus-it500-mqtt@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the salus-it500-mqtt@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ovi/.npm/_logs/2020-08-29T09_21_02_263Z-debug.log`

**Comment by ovidiu31** [comment]
i've got it working but trying to understand how to get the readings with home assistant

**Comment by ovidiu31** [comment]
Got it fixed... rename settings.sample.json to settings.json was the solution
